#!/bin/bash

HOME=$PWD
REPO_FILES=$HOME/java/classifier
CLASSIFIER=$HOME/node_modules/java/src-java/classifier

JAVA_FILES=/home/david/Dropbox/workspace/ChessProject/src/classifier
DATA_FILES=/home/david/Dropbox/workspace/ChessProject

if [ ! -d $CLASSIFIER ]; then
   mkdir $CLASSIFIER
fi

cp $DATA_FILES/*.txt ./data/

FILES_TEXT=""

pushd .

cd ./java/classifier

cp $JAVA_FILES/* ./

for file in *
do
   if [[ -f $file ]]; then
      extension="${file##*.}"

      if [ $extension == "java" ]; then
         FILES_TEXT="$file $FILES_TEXT"
      fi
   fi
done

echo javac $FILES_TEXT
javac $FILES_TEXT

cp *.class $CLASSIFIER/

popd
