#!/bin/bash

HOME=$PWD
REPO_FILES=$HOME/java/classifier
CLASSIFIER=$HOME/node_modules/java/src-java/classifier

FILES_TEXT=""

pushd .

cd ./java/classifier

cp $JAVA_FILES/* ./

for file in *
do
   if [[ -f $file ]]; then
      extension="${file##*.}"

      if [ $extension == "java" ]; then
         FILES_TEXT="$file $FILES_TEXT"
      fi
   fi
done

echo javac $FILES_TEXT
javac $FILES_TEXT

echo $CLASSIFIER/
for file in *
do 
  echo $file
  cp $file ... $CLASSIFIER/
done

popd
